from pydantic_settings import SettingsConfigDict

from base_config import BaseConfig


class Config(BaseConfig):
    spotify_client_id: str
    spotify_client_secret: str
    spotify_redirect_uri: str

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", env_ignore_empty=True)

    tastebud_playlist_watermark: str = "Playlist automatically generated by TasteBud."


CONFIG = Config()
